@startuml clases
!define Sprite pygame.sprite.Sprite
!define ABC abc.ABC
!define abstractmethod abc.abstractmethod

class Dad {
    -- Atributos --
    - int vida
    - list images_animation
    - int current_image
    - Surface personaje_imagen
    - Rect rect
    - int animation_time
    - int last_update
    - int contador
    - list bats_array
    
    -- Métodos --
    + __init__(self, animation, animation_time, pet)
    + abstract animacion(self)
    + abstract draw(self, screen)
}

class Bat {
    -- Atributos --
    - int velocidad_x
    - Sound audio
    
    -- Métodos --
    + __init__(self, vida, animation, animation_time, pet)
    + animacion(self)
    + draw(self, screen)
    + mover(self)
    + add_array(self, array, pet)
    + appear(self, screen, array)
    + delete(self, delete_bat)
}

class Gusano {
    -- Atributos --
    - int velocidad_x
    - int mitad
    - Sound audio
    
    -- Métodos --
    + __init__(self, vida, animation, animation_time, pet)
    + animacion(self)
    + draw(self, screen)
    + mover(self)
    + add_array(self, array, pet)
    + appear(self, screen, array)
    + delete(self, delete_bat)
}

Dad <|-- Bat
Dad <|-- Gusano
Dad ..> ABC : implements
Dad ..> Sprite : extends

@enduml
